apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      ImagePullSecrets:
        - name: ecr
      containers:
        - name: order
          image: uri_do_repositorio_no_ECR_AWS
          ports:
            - containerPort: 443
          envFrom:
            - configMapRef:
                name: config-map
