apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      volumes:
        - name: tls
          secret:
            secretName: tls
      ImagePullSecrets:
        - name: ecr
      containers:
        - name: order
          image: uri_do_repositorio_no_ECR_AWS
          ports:
            - containerPort: 4443
          envFrom:
            - configMapRef:
                name: config-map
          volumeMounts:
            - name: tls
              readOnly: true
              mountPath: /nsse-backend/certificates
          resources:
            requests:
              memory: "64Mi"
              cpu: "64m"
            limits:
              memory: "64Mi"
              cpu: "64m"
