apiVersion: v1
kind: Service
metadata:
  name: order
  annotations:
    service.kubernetes.io/topology-mode: Auto #Topology Aware Routing - para encaminhar
    # o trafego para os pods que estao na mesma zona de disponibilidade (de preferencia)
    # para aumentar a performance e reduzir a latencia.
spec:
  type: NodePort
  selector:
    app: order
  ports:
    - port: 4443
      #targetPort: 80 =  #caso nao definido, assumira o valor do port por padrao
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30000
