healthCheckerDeployment:
  image: uri_do_repositorio_no_ECR_AWS
  containerPort: 4443
  nodePort: 30005
  configMap: nsse-config-map-prod
  replicaCount: 1
  serviceAccount: nsse-sa-prod
  imagePullSecrets: nsse-ecr-image-pull-secrets-prod
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  volumes:
    - name: kestrel
      secret:
        secretName: kestrel-certificate
  volumeMounts:
    - name: kestrel
      readOnly: true
      mountPath: /nsse-backend/certificates/kestrel
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "64Mi"
      cpu: "50m"
  livenessProbe:
    httpGet:
      path: /healthchecks/health
      port: 4443
      scheme: HTTPS
    successThreshold: 1
    failureThreshold: 3
    initialDelaySeconds: 120
    timeoutSeconds: 15
    periodSeconds: 60
  readinessProbe:
    httpGet:
      path: /healthchecks/health
      port: 4443
      scheme: HTTPS
    successThreshold: 1
    failureThreshold: 3
    initialDelaySeconds: 3
    timeoutSeconds: 15
    periodSeconds: 3
