namespace: nsse
namePrefix: "nsse-"
nameSuffix: "-prod"
commonLabels:
  application: not-so-simple-ecommerce
resources:
  - infrastructure/namespace.yml
  - infrastructure/config-map.yml
  - infrastructure/service-account.yml
  - infrastructure/secrets/ecr-image-pull-credentials.yml
  - infrastructure/secrets/kestrel-certificate.yml
  - infrastructure/secrets/mongo-certificate.yml
  - infrastructure/ingress.yml
  - infrastructure/network-policies/ingress.yml
  - infrastructure/network-policies/egress.yml

helmGlobals:
  chartHome: application

helmCharts:
  - name: health-checker
    repo: health-checker
    releaseName: health-checker
    valuesFile: application/health-checker/values.yaml

  - name: identity-server
    repo: identity-server
    releaseName: identity-server
    valuesFile: application/identity-server/values.yaml

  - name: invoice-generator
    repo: invoice-generator
    releaseName: invoice-generator
    valuesFile: application/invoice-generator/values.yaml

  - name: notificator
    repo: notificator
    releaseName: notificator
    valuesFile: application/notificator/values.yaml

  - name: main
    repo: main
    releaseName: main
    valuesFile: application/main/values.yaml

  - name: order
    repo: order
    releaseName: order
    valuesFile: application/order/values.yaml

images:
  - name: uri_do_dkr.ecr...amazonaws.com/nsse/production/order
    newName: uri_do_dkr.ecr...amazonaws.com/nsse/production/order
    newTag: latest

  - name: uri_do_dkr.ecr...amazonaws.com/nsse/production/main
    newName: uri_do_dkr.ecr...amazonaws.com/nsse/production/main
    newTag: latest

  - name: uri_do_dkr.ecr...amazonaws.com/nsse/production/identiryserver
    newName: uri_do_dkr.ecr...amazonaws.com/nsse/production/identiryserver
    newTag: latest

  - name: uri_do_dkr.ecr...amazonaws.com/nsse/production/notificator
    newName: uri_do_dkr.ecr...amazonaws.com/nsse/production/notificator
    newTag: latest

  - name: uri_do_dkr.ecr...amazonaws.com/nsse/production/health-checker
    newName: uri_do_dkr.ecr...amazonaws.com/nsse/production/health-checker
    newTag: latest

  - name: uri_do_dkr.ecr...amazonaws.com/nsse/production/invoice-generator
    newName: uri_do_dkr.ecr...amazonaws.com/nsse/production/invoice-generator
    newTag: latest
#Necessario abrir o tunel para executar o comando abaixo:

#aws ssm start-session --target i-xxx --document-name AWS-StartPortForwardingSession --parameters 'portNumber=6443,localPortNumber=6443'
#export KUBECONFIG=/etc/kubernetes/admin.conf
#kubectl get nodes

#O comando abaixo chamara o arquivo kustomization.yml
#kubectl apply -k .

#kubectl get deploy -n nsse
#kubectl get deploy,po -n nsse

#ncomando para construir tudo usando o --enable-helm
#kustomize build --enable-helm | kubectl apply -f -
#kubectl get all -n nsse
#kubectl get all -n nsse -w (watch - para assistir a criacao)
