namespace: nsse
namePrefix: "-prod"
nameSuffix: "nsse-"
commonLabels:
  application: not-so-simple-ecommerce
resources:
  - application/namespace.yml
  - application/config-map.yml
  - application/service-account.yml
  - application/secrets/ecr-image-pull-credentials.yml
  - application/secrets/kestrel-certificate.yml
  - application/secrets/mongo-certificate.yml
  - application/health-checker/deployment.yml
  - application/identity-server/deployment.yml
  - application/invoice-generator/deployment.yml
  - application/main/deployment.yml
  - application/notificator/deployment.yml
  - application/order/deployment.yml
  - application/health-checker/service.yml
  - application/identity-server/service.yml
  - application/invoice-generator/service.yml
  - application/main/service.yml
  - application/main/hpa.yml
  - application/notificator/service.yml
  - application/order/service.yml
  - application/identity-server/hpa.yml
  - application/invoice-generator/hpa.yml
  - application/main/hpa.yml
  - application/notificator/hpa.yml
  - application/order/hpa.yml
  - application/ingress.yml
  - infrastructure/network-policies/ingress.yml
  - infrastructure/network-policies/egress.yml
images:
  - name: uri_do_dkr.ecr...amazonaws.com/nsse/production/order
    newName: uri_do_dkr.ecr...amazonaws.com/nsse/production/order
    newTag: latest

  - name: uri_do_dkr.ecr...amazonaws.com/nsse/production/main
    newName: uri_do_dkr.ecr...amazonaws.com/nsse/production/main
    newTag: latest

  - name: uri_do_dkr.ecr...amazonaws.com/nsse/production/identiryserver
    newName: uri_do_dkr.ecr...amazonaws.com/nsse/production/identiryserver
    newTag: latest

  - name: uri_do_dkr.ecr...amazonaws.com/nsse/production/notificator
    newName: uri_do_dkr.ecr...amazonaws.com/nsse/production/notificator
    newTag: latest

  - name: uri_do_dkr.ecr...amazonaws.com/nsse/production/health-checker
    newName: uri_do_dkr.ecr...amazonaws.com/nsse/production/health-checker
    newTag: latest

  - name: uri_do_dkr.ecr...amazonaws.com/nsse/production/invoice-generator
    newName: uri_do_dkr.ecr...amazonaws.com/nsse/production/invoice-generator
    newTag: latest
#Necessario abrir o tunel para executar o comando abaixo:

#aws ssm start-session --target i-xxx --document-name AWS-StartPortForwardingSession --parameters 'portNumber=6443,localPortNumber=6443'
#export KUBECONFIG=/etc/kubernetes/admin.conf
#kubectl get nodes

#O comando abaixo chamara o arquivo kustomization.yml
#kubectl apply -k .

#kubectl get deploy -n nsse
#kubectl get deploy,po -n nsse
