namespace: nsse
namePrefix: "-prod"
nameSuffix: "nsse-"
commonLabels:
  application: not-so-simple-ecommerce
resources:
  - namespace.yml
  - config-map.yml
  - secrets/ecr-image-pull-credentials.yml
  - secrets/kestrel-certificate.yml
  - secrets/mongo-certificate.yml
  - order/deployment.yml
  - main/deployment.yml
images:
  - name: uri_do_dkr.ecr...amazonaws.com/nsse/production/order
  - newName: uri_do_dkr.ecr...amazonaws.com/nsse/production/order
  - newTag: latest

  - name: uri_do_dkr.ecr...amazonaws.com/nsse/production/main
  - newName: uri_do_dkr.ecr...amazonaws.com/nsse/production/main
  - newTag: latest
#Necessario abrir o tunel para executar o comando abaixo:

#aws ssm start-session --target i-xxx --document-name AWS-StartPortForwardingSession --parameters 'portNumber=6443,localPortNumber=6443'
#export KUBECONFIG=/etc/kubernetes/admin.conf
#kubectl get nodes

#O comando abaixo chamara o arquivo kustomization.yml
#kubectl apply -k .

#kubectl get deploy -n nsse
#kubectl get deploy,po -n nsse
