identityServerDeployment:
  image: uri_do_repositorio_no_ECR_AWS
  containerPort: 4443
  nodePort: 30004
  configMap: nsse-config-map-prod
  replicaCount: 1
  serviceAccount: nsse-sa-prod
  imagePullSecrets: nsse-ecr-image-pull-secrets-prod
  autoScaling:
    minReplicas: 1
    maxReplicas: 3
    averageCpuUtilization: 50
    scaleDown:
      stabilizationWindowSeconds: 15
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 15
          selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 2
          periodSeconds: 15
          selectPolicy: Max
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  volumes:
    - name: kestrel
      secret:
        secretName: kestrel-certificate
  volumeMounts:
    - name: kestrel
      readOnly: true
      mountPath: /nsse-backend/certificates/kestrel
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "64Mi"
      cpu: "50m"
  livenessProbe:
    httpGet:
      path: /identity-server/health
      port: 4443
      scheme: HTTPS
    successThreshold: 1
    failureThreshold: 3
    initialDelaySeconds: 120
    timeoutSeconds: 15
    periodSeconds: 60
  readinessProbe:
    httpGet:
      path: /identity-server/health
      port: 4443
      scheme: HTTPS
    successThreshold: 1
    failureThreshold: 3
    initialDelaySeconds: 3
    timeoutSeconds: 15
    periodSeconds: 3
