apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.invoiceGeneratorDeployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      topologySpreadConstraints:
      {{- range .Values.invoiceGeneratorDeployment.topologySpreadConstraints }}
        - maxSkew: {{ .maxSkew }}
          topologyKey: {{ .topologyKey }}
          whenUnsatisfiable: {{ .whenUnsatisfiable }}
          labelSelector:
            matchLabels:
              app: {{ $.Release.Name }}
      {{- end}}
      #para definir um usuario NAO root, usamos o Security Context
      #acessando o po: kubectl -n nsse exec -it "nome_do_pod" -- /bin/sh
      #digitando o comando id, podemos ver o usuario dentro do container
      securityContext:
        {{- toYaml .Values.invoiceGeneratorDeployment.securityContext | nindent 8 }}
      serviceAccount: {{ .Values.invoiceGeneratorDeployment.serviceAccount }}
      volumes:
        {{- toYaml .Values.invoiceGeneratorDeployment.volumes | nindent 8}}
      ImagePullSecrets:
        - name: {{ .Values.invoiceGeneratorDeployment.imagePullSecrets }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.invoiceGeneratorDeployment.image }}
        ports:
        - containerPort: {{ .Values.invoiceGeneratorDeployment.containerPort }}
        envFrom:
        - configMapRef:
            name: {{ .Values.invoiceGeneratorDeployment.configMap }}
        volumeMounts:
          {{- toYaml .Values.invoiceGeneratorDeployment.volumeMounts | nindent 10 }}
        resources:
          {{- toYaml .Values.invoiceGeneratorDeployment.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.invoiceGeneratorDeployment.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.invoiceGeneratorDeployment.readinessProbe | nindent 10 }}
