apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-server
  template:
    metadata:
      labels:
        app: identity-server
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: identity-server

      #para definir um usuario NAO root, usamos o Security Context
      #acessando o po: kubectl -n nsse exec -it "nome_do_pod" -- /bin/sh
      #digitando o comando id, podemos ver o usuario dentro do container
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      serviceAccount: nsse-sa-prod
      volumes:
        - name: kestrel
          secret:
            secretName: kestrel-certificate
      ImagePullSecrets:
        - name: ecr-image-pull-credentials
      containers:
        - name: identity-server
          image: uri_do_repositorio_no_ECR_AWS
          ports:
            - containerPort: 4443
          envFrom:
            - configMapRef:
                name: config-map
          volumeMounts:
            - name: kestrel
              readOnly: true
              mountPath: /nsse-backend/certificates/kestrel
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
            livenessProbe:
              httpGet:
                path: /identity/health
                port: 4443
                scheme: HTTPS
              successThreshold: 1
              failureThreshold: 3
              initialDelaySeconds: 120
              timeoutSeconds: 15
              periodSeconds: 60
            readinessProbe:
              httpGet:
                path: /identity/health
                port: 4443
                scheme: HTTPS
              successThreshold: 1
              failureThreshold: 3
              initialDelaySeconds: 3
              timeoutSeconds: 15
              periodSeconds: 3
