apiVersion: v1
kind: Service
metadata:
  name: identity-server
  annotations:
    service.kubernetes.io/topology-mode: Auto
spec:
  type: NodePort
  selector:
    app: identity-server
  ports:
    - port: 4443
      nodePort: 30004
