1apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      topologySpreadConstraints: #obviamente, so funciona quando usado com diversas replicas
        - maxSkew: 1 #diferenca entre as zonas
          topologyKey: topology.kubernetes.io/zone #restricao por zona
          whenUnsatisfiable: DoNotSchedule #quando a condicao nao for satisfeita, nao faca o agendamento
          labelSelector:
            matchLabels:
              app: main
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      serviceAccount: nsse-sa-prod
      volumes:
        - name: kestrel
          secret:
            secretName: kestrel-certificate
        - name: mongo
          secret:
            secretName: mongo-certificate
      ImagePullSecrets:
        - name: ecr-image-pull-credentials
      containers:
        - name: main
          image: uri_do_repositorio_no_ECR_AWS
          ports:
            - containerPort: 4443
          envFrom:
            - configMapRef:
                name: config-map
          volumeMounts:
            - name: kestrel
              readOnly: true
              mountPath: /nsse-backend/certificates/kestrel
            - name: mongo
              readOnly: true
              mountPath: /nsse-backend/certificates/mongo
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "50m"
            livenessProbe:
              httpGet:
                path: /main/health
                port: 4443
                scheme: HTTPS
              successThreshold: 1
              failureThreshold: 3
              initialDelaySeconds: 120
              timeoutSeconds: 15
              periodSeconds: 60
            readinessProbe:
              httpGet:
                path: /main/health
                port: 4443
                scheme: HTTPS
              successThreshold: 1
              failureThreshold: 3
              initialDelaySeconds: 3
              timeoutSeconds: 15
              periodSeconds: 3
