apiVersion: v1
kind: Service
metadata:
  name: main
  annotations:
    service.kubernetes.io/topology-mode: Auto
spec:
  type: NodePort
  selector:
    app: main
  ports:
    - port: 4443
      nodePort: 30002
